"""add risk reasons

Revision ID: 0395cfc98c19
Revises: ec402395fe7a
Create Date: 2026-09-19 17:53:25.177825
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0395cfc98c19'
down_revision: Union[str, Sequence[str], None] = 'ec402395fe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_checks', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_checks', 'risk_reasons')
    # ### end Alembic commands ###