"""add security type

Revision ID: ec402395fe7a
Revises: 0001
Create Date: 2026-09-19 16:37:39.416503
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ec402395fe7a'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_checks', sa.Column('security_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_checks', 'security_type')
    # ### end Alembic commands ###